repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    exclude: \.(svg|png|jpg|jpeg|gif|ico|webp)$
  - id: end-of-file-fixer
    exclude: \.(svg|png|jpg|jpeg|gif|ico|webp)$

- repo: https://github.com/psf/black
  rev: 26.3.1
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
  - id: ruff
    args: [--fix]
